name: Feature Request
description: Suggest new content or mechanics for Mindustry
title: "Title"
labels: [feature request]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the content or mechanics you are proposing."
    validations:
      required: true
  - type: textarea
    id: description2
    attributes:
      label: "Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche."
    validations:
      required: true
  - type: checkboxes
    id: confirmation
    attributes:
      label: Before making this issue, check the boxes below to confirm that you have acknowledged them.
      options:
        - label: I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
          required: true
        - label: I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
          required: true
        - label: I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
          required: true
